{% set name = "apache-airflow-providers-postgres" %}
{% set version = "6.2.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_postgres-{{ version }}.tar.gz
  sha256: 5487374cfa9c93466b1227daad5290b781bcae6a40ee860ca02076741aac31e8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.10.0
    - apache-airflow-providers-common-sql >=1.23.0
    - psycopg2-binary >=2.9.9
    - asyncpg >=0.30.0

test:
  imports:
    - airflow.providers.postgres
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-postgres for Apache Airflow
  license: Apache-2.0
  license_file: src/airflow/providers/postgres/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
