{% set name = "apache-airflow-providers-postgres" %}
{% set version = "5.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-postgres-{{ version }}.tar.gz
  sha256: 964903d43b2af3a9a3ff0b2f2061f416a9cc4e0eaa1ecfa13ec334ff0f5ecdb6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=67.2.0
    - pip
  run:
    - python >=3.7
    - apache-airflow-providers-common-sql >=1.3.1
    - apache-airflow >=2.4.0
    - psycopg2-binary >=2.8.0

test:
  imports:
    - airflow.providers.postgres
    - airflow.providers.postgres.hooks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-postgres package
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
