{% set name = "apache-airflow-providers-postgres" %}
{% set version = "5.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_postgres-{{ version }}.tar.gz
  sha256: 9460305195f838d03cca05099df00941ca703df0a9a4711176a3d618ed7c735c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8,<4.dev0
    - apache-airflow-providers-common-sql >=1.14.1
    - apache-airflow >=2.8.0
    - psycopg2-binary >=2.9.4

test:
  imports:
    - airflow.providers.postgres
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-postgres for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/postgres/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
